name: Update Notion Movies

on:
   schedule:
     - cron: "0 4 * * *" # Run every day at 4:00
   workflow_dispatch:    # Allows manual execution

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build ./src/NotionMovieUpdater.sln --no-restore --configuration Release
        
      - name: Run application
        run: dotnet run --project ./src/NotionMovieUpdater/NotionMovieUpdater.csproj --configuration Release --no-build
        env:
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
